;; .yas-setup.el for my elixir-mode
(defun module-model ()
  (let* ((curr-file (file-name-directory buffer-file-name))
         (parent-dir (file-name-nondirectory (directory-file-name curr-file)))
         (capitalized-parent (capitalize parent-dir))
         (capitalized-name (mapconcat #'capitalize (split-string capitalized-parent "_") ""))
         )
    capitalized-name
    )
  )
(defun module-file-name ()
  (let* ((curr-file (file-name-base buffer-file-name))
         (splitted-file (split-string curr-file "_"))
         (capitalized-file (mapconcat 'capitalize splitted-file))
         )
    capitalized-file)
  )

(defun module-html-helper ()
  (let* ((str (file-name-base buffer-file-name))
         (parts (split-string str "_"))
         (capitalized-parts (mapcar #'capitalize (butlast parts)))
         (last-part (upcase (car (last parts)))))
    (string-join (append capitalized-parts (list last-part)) ""))
  )

(defun module-dir ()
  (let* ((parent-dir (file-name-parent-directory buffer-file-name))
         (grandparent-dir (file-name-parent-directory parent-dir))
         (dir-name (file-name-nondirectory (directory-file-name grandparent-dir)))
         (capitalized-name (mapconcat #'capitalize (split-string dir-name "_") "")))
    capitalized-name)
  )
